apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: platform
  sources:
    # 1. Helm chart source
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.1.1
      helm:
        valueFiles:
          - $values/helm-values/external-secrets.yaml

    # 2. Git repo source (for your values)
    - repoURL: https://github.com/smooti/platform-bootstrap.git
      targetRevision: HEAD
      ref: values     # <--- makes $values available

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
