apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: platform
  sources:
    # 1. Helm chart source
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.6.1
      helm:
        valueFiles:
          - $values/helm-values/kyverno.yaml

    # 2. Git repo source (for your values)
    - repoURL: https://github.com/<you>/<repo>.git
      targetRevision: argo
      ref: values     # <--- makes $values available

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
